services:
  db:
    image: postgres:17.4
    volumes:
      - pg:/var/lib/postgresql/data:cached
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  meilisearch:
    image: getmeili/meilisearch:prototype-japanese-13
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data
    environment:
      MEILI_ENV: development
      MEILI_MASTER_KEY: zenbunMasterKey
  app:
    build: .
    command: elixir -S mix phx.server
    volumes:
      - .:/app:cached
    working_dir: /app
    ports:
      - "4000:4000"
    depends_on:
      - db
      - meilisearch
    tty: true
volumes:
  pg:
  meili_data:
